// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SistemaTikets.Infrastructure.Persistence;

#nullable disable

namespace SistemaTikets.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SistemaTikets.Domain.Entities.Area", b =>
                {
                    b.Property<int>("IdArea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_area");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdArea"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdArea");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("areas", (string)null);
                });

            modelBuilder.Entity("SistemaTikets.Domain.Entities.Comentario", b =>
                {
                    b.Property<int>("IdComentario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_comentario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdComentario"));

                    b.Property<DateTime>("FechaComentario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_comentario")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("IdSolicitud")
                        .HasColumnType("integer")
                        .HasColumnName("id_solicitud");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("texto");

                    b.HasKey("IdComentario");

                    b.HasIndex("IdSolicitud");

                    b.HasIndex("IdUsuario");

                    b.ToTable("comentarios", (string)null);
                });

            modelBuilder.Entity("SistemaTikets.Domain.Entities.Estado", b =>
                {
                    b.Property<int>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_estado");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEstado"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdEstado");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("estados", (string)null);
                });

            modelBuilder.Entity("SistemaTikets.Domain.Entities.Prioridad", b =>
                {
                    b.Property<int>("IdPrioridad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_prioridad");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPrioridad"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdPrioridad");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("prioridades", (string)null);
                });

            modelBuilder.Entity("SistemaTikets.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_rol");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdRol");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("SistemaTikets.Domain.Entities.Solicitud", b =>
                {
                    b.Property<int>("IdSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_solicitud");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSolicitud"));

                    b.Property<string>("ArchivoUrl")
                        .HasColumnType("text")
                        .HasColumnName("archivo_url");

                    b.Property<string>("Asunto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("asunto");

                    b.Property<string>("Codigo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<DateTime?>("FechaAsignacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_asignacion");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("IdArea")
                        .HasColumnType("integer")
                        .HasColumnName("id_area");

                    b.Property<int?>("IdAsignadoPor")
                        .HasColumnType("integer")
                        .HasColumnName("id_asignado_por");

                    b.Property<int>("IdEstado")
                        .HasColumnType("integer")
                        .HasColumnName("id_estado");

                    b.Property<int?>("IdGestorAsignado")
                        .HasColumnType("integer")
                        .HasColumnName("id_gestor_asignado");

                    b.Property<int>("IdPrioridad")
                        .HasColumnType("integer")
                        .HasColumnName("id_prioridad");

                    b.Property<int>("IdSolicitante")
                        .HasColumnType("integer")
                        .HasColumnName("id_solicitante");

                    b.Property<int>("IdTipoSolicitud")
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo_solicitud");

                    b.HasKey("IdSolicitud");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("IdArea");

                    b.HasIndex("IdAsignadoPor");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdGestorAsignado");

                    b.HasIndex("IdPrioridad");

                    b.HasIndex("IdSolicitante");

                    b.HasIndex("IdTipoSolicitud");

                    b.ToTable("solicitudes", (string)null);
                });

            modelBuilder.Entity("SistemaTikets.Domain.Entities.TipoSolicitud", b =>
                {
                    b.Property<int>("IdTipoSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo_solicitud");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTipoSolicitud"));

                    b.Property<int>("IdArea")
                        .HasColumnType("integer")
                        .HasColumnName("id_area");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdTipoSolicitud");

                    b.HasIndex("IdArea");

                    b.ToTable("tipos_solicitud", (string)null);
                });

            modelBuilder.Entity("SistemaTikets.Domain.Entities.TrazabilidadSolicitud", b =>
                {
                    b.Property<int>("IdTrazabilidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_trazabilidad");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTrazabilidad"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("accion");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("FechaEvento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_evento")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("IdSolicitud")
                        .HasColumnType("integer")
                        .HasColumnName("id_solicitud");

                    b.Property<int?>("IdUsuarioActor")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario_actor");

                    b.HasKey("IdTrazabilidad");

                    b.HasIndex("IdSolicitud");

                    b.HasIndex("IdUsuarioActor");

                    b.ToTable("trazabilidad_solicitudes", (string)null);
                });

            modelBuilder.Entity("SistemaTikets.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuario"));

                    b.Property<DateTime>("FechaCreacionUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion_usuario")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("IdAreaAsignada")
                        .HasColumnType("integer")
                        .HasColumnName("id_area_asignada");

                    b.Property<int?>("IdCreadoPor")
                        .HasColumnType("integer")
                        .HasColumnName("id_creado_por");

                    b.Property<int>("IdRol")
                        .HasColumnType("integer")
                        .HasColumnName("id_rol");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdAreaAsignada");

                    b.HasIndex("IdCreadoPor");

                    b.HasIndex("IdRol");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("SistemaTikets.Domain.Entities.Comentario", b =>
                {
                    b.HasOne("SistemaTikets.Domain.Entities.Solicitud", "Solicitud")
                        .WithMany("Comentarios")
                        .HasForeignKey("IdSolicitud")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaTikets.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Comentarios")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Solicitud");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaTikets.Domain.Entities.Solicitud", b =>
                {
                    b.HasOne("SistemaTikets.Domain.Entities.Area", "Area")
                        .WithMany("Solicitudes")
                        .HasForeignKey("IdArea")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaTikets.Domain.Entities.Usuario", "AsignadoPor")
                        .WithMany("SolicitudesAsignadasPor")
                        .HasForeignKey("IdAsignadoPor")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaTikets.Domain.Entities.Estado", "Estado")
                        .WithMany("Solicitudes")
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaTikets.Domain.Entities.Usuario", "GestorAsignado")
                        .WithMany("SolicitudesAsignadas")
                        .HasForeignKey("IdGestorAsignado")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaTikets.Domain.Entities.Prioridad", "Prioridad")
                        .WithMany("Solicitudes")
                        .HasForeignKey("IdPrioridad")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaTikets.Domain.Entities.Usuario", "Solicitante")
                        .WithMany("SolicitudesCreadas")
                        .HasForeignKey("IdSolicitante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaTikets.Domain.Entities.TipoSolicitud", "TipoSolicitud")
                        .WithMany("Solicitudes")
                        .HasForeignKey("IdTipoSolicitud")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("AsignadoPor");

                    b.Navigation("Estado");

                    b.Navigation("GestorAsignado");

                    b.Navigation("Prioridad");

                    b.Navigation("Solicitante");

                    b.Navigation("TipoSolicitud");
                });

            modelBuilder.Entity("SistemaTikets.Domain.Entities.TipoSolicitud", b =>
                {
                    b.HasOne("SistemaTikets.Domain.Entities.Area", "Area")
                        .WithMany("TiposSolicitud")
                        .HasForeignKey("IdArea")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("SistemaTikets.Domain.Entities.TrazabilidadSolicitud", b =>
                {
                    b.HasOne("SistemaTikets.Domain.Entities.Solicitud", "Solicitud")
                        .WithMany("Trazabilidades")
                        .HasForeignKey("IdSolicitud")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaTikets.Domain.Entities.Usuario", "UsuarioActor")
                        .WithMany("Trazabilidades")
                        .HasForeignKey("IdUsuarioActor")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Solicitud");

                    b.Navigation("UsuarioActor");
                });

            modelBuilder.Entity("SistemaTikets.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("SistemaTikets.Domain.Entities.Area", "AreaAsignada")
                        .WithMany("UsuariosAsignados")
                        .HasForeignKey("IdAreaAsignada")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaTikets.Domain.Entities.Usuario", "CreadoPor")
                        .WithMany("UsuariosCreados")
                        .HasForeignKey("IdCreadoPor")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaTikets.Domain.Entities.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AreaAsignada");

                    b.Navigation("CreadoPor");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("SistemaTikets.Domain.Entities.Area", b =>
                {
                    b.Navigation("Solicitudes");

                    b.Navigation("TiposSolicitud");

                    b.Navigation("UsuariosAsignados");
                });

            modelBuilder.Entity("SistemaTikets.Domain.Entities.Estado", b =>
                {
                    b.Navigation("Solicitudes");
                });

            modelBuilder.Entity("SistemaTikets.Domain.Entities.Prioridad", b =>
                {
                    b.Navigation("Solicitudes");
                });

            modelBuilder.Entity("SistemaTikets.Domain.Entities.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SistemaTikets.Domain.Entities.Solicitud", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("Trazabilidades");
                });

            modelBuilder.Entity("SistemaTikets.Domain.Entities.TipoSolicitud", b =>
                {
                    b.Navigation("Solicitudes");
                });

            modelBuilder.Entity("SistemaTikets.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("SolicitudesAsignadas");

                    b.Navigation("SolicitudesAsignadasPor");

                    b.Navigation("SolicitudesCreadas");

                    b.Navigation("Trazabilidades");

                    b.Navigation("UsuariosCreados");
                });
#pragma warning restore 612, 618
        }
    }
}
